---
deploy_role: "exchange"
rollsite: "{{ exchange.get('rollsite',{}) }}"
osx: "{{ exchange.get('osx',{}) }}"
partyid: "{{ exchange.get('partyid','default') }}"
clustermanager: "{{ exchange.get('clustermanager',{}) }}"
