---
deploy_role: "guest"
partyid: "{{ guest.get('partyid',9999) }}"
eggroll: "{{ guest.get('eggroll',{}) }}"
rollsite: "{{ guest.get('rollsite',{}) }}"
clustermanager: "{{ guest.get('clustermanager',{}) }}"
nodemanager: "{{ guest.get('nodemanager',{}) }}"
side: "{{ guest.get('side',{}) }}"
db: "{{ guest.get('mysql',{}) }}"
fateboard: "{{ guest.get('fateboard',{}) }}"
fate_flow: "{{ guest.get('fate_flow',{}) }}"
zk: "{{ guest.get('zk',{}) }}"
servings: "{{ guest.get('servings',{}) }}"
spark: "{{ guest.get('spark',{}) }}"
hive: "{{ guest.get('hive',{}) }}"
hdfs: "{{ guest.get('hdfs',{}) }}"
rabbit: "{{ guest.get('rabbitmq',{}) }}"
pulsar: "{{ guest.get('pulsar',{}) }}"
nginx: "{{ guest.get('nginx',{}) }}"
model_store: "{{ guest.get('model_store',{}) }}"
osx: "{{ guest.get('osx',{}) }}"
dashboard: "{{ guest.get('dashboard',{}) }}"