- name: "mkdir({{deploy_mode}}): {{lbase}}/{{pname}}/{{role_name}}"
  file:
    path: "{{lbase}}/{{pname}}/{{role_name}}"
    state: directory
    mode: 0750

- name: "mkdir({{deploy_mode}}): {{dbase}}/{{pname}}/{keys,eggroll}"
  file:
    path: "{{dbase}}/{{pname}}/{{item}}"
    state: directory
    mode: 0750
  with_items:
  - keys
  - eggroll

- name: "mkdir({{deploy_mode}}): {{pbase}}/{{pname}}/{bin,sql}"
  file:
    path: "{{pbase}}/{{pname}}/{{item}}"
    state: directory
    mode: 0750
  with_items:
  - bin
  - sql

- name: "update({{deploy_mode}}): {{pbase}}/{{pname}}/bin/init_env.sh"
  template:
    src: "init_env.sh.jinja"
    dest: "{{pbase}}/{{pname}}/bin/init_env.sh"
    mode: 0755

- name: "Copy: jcheck.py {{pbase}}/{{pname}}/tools/jcheck.py"
  copy:
    src: "jcheck.py"
    dest: "{{pbase}}/{{pname}}/tools/jcheck.py"

- name: "check({{deploy_mode}}): {{pbase}}/{{pname}}/bin/debug"
  stat:
    path: "{{pbase}}/{{pname}}/bin/debug"
  register: eggroll_debug_stat

- name: "untar({{deploy_mode}}): debug.tar.gz"
  unarchive:
    src: "debug.tar.gz"
    dest: "{{pbase}}/{{pname}}/bin"
  when: eggroll_debug_stat.stat.exists == False

- name: "check({{deploy_mode}}): {{pbase}}/{{pname}}/{{role_name}}"
  stat:
    path: "{{pbase}}/{{pname}}/{{role_name}}/conf/eggroll.properties"
  register: eggroll_stat

- name: "untar({{deploy_mode}}): {{role_name}}.tar.gz"
  unarchive:
    src: "{{role_name}}.tar.gz"
    dest: "{{pbase}}/{{pname}}/"
  when: eggroll_stat.stat.exists == False

- name: "delete({{deploy_mode}}): {{pbase}}/{{pname}}/{{role_name}}/logs"
  file:
    path: "{{pbase}}/{{pname}}/{{role_name}}/logs"
    state: absent
  when: eggroll_stat.stat.exists == False

- name: "link({{deploy_mode}}): {{lbase}}/{{pname}}/{{role_name}}"
  file:
    src: "{{lbase}}/{{pname}}/{{role_name}}"
    dest: "{{pbase}}/{{pname}}/{{role_name}}/logs"
    state: link
  when: eggroll_stat.stat.exists == False

- name: "Copy: fate-eggroll.sh {{pbase}}/{{pname}}/{{role_name}}/bin"
  copy:
    src: "eggroll.sh"
    dest: "{{pbase}}/{{pname}}/eggroll/bin/fate-eggroll.sh"
    mode: 0755
